name: ops Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
        dummy: [1,2,3,4,5,6,7,8,9,0]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Enable core dumps
        run: |
          # unlimited core size
          ulimit -c unlimited
          # send cores to /tmp with a predictable name
          echo '/tmp/core-%e-%p-%t' | sudo tee /proc/sys/kernel/core_pattern

      - name: Install tox
        run: pip install tox~=4.2

      - name: Run unit tests 0
        run: tox -e unit

      - name: Run unit tests 1
        run: tox -e unit

      - name: Run unit tests 2
        run: tox -e unit

      - name: Run unit tests 3
        run: tox -e unit

      - name: Run unit tests 4
        run: tox -e unit

      - name: Run unit tests 5
        run: tox -e unit

      - name: Run unit tests 6
        run: tox -e unit

      - name: Run unit tests 7
        run: tox -e unit

      - name: Run unit tests 8
        run: tox -e unit

      - name: Run unit tests 9
        run: tox -e unit

      - name: Run tracing unit tests
        run: cd tracing && tox -e unit

      - name: Upload core dumps
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: core-dumps
          path: /tmp/core-*
