name: ops Integration Tests

on:
  pull_request:  # remove before merge
  workflow_dispatch:
  schedule:
    - cron:  '42 7 25 * *'

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        preset: ['k8s', 'microk8s']
        test-group: [1, 2, 3, 4]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v5
      - run: |
          # Report selected tests
          uvx tox -e integration -q \
            -- \
            --collect-only -q \
            --test-group-random-seed=0 \
            --test-group-count=4 \
            --test-group=${{ matrix.test-group }} |
          sed -r 's/\x1B\[[0-9;]*[a-zA-Z]//g' |
          awk 'BEGIN { print "## Selected tests\n```" } { print } END { print "```" }' >> $GITHUB_STEP_SUMMARY
      - run: |
           # Work around https://github.com/jnsgruk/concierge/issues/30
           sudo apt-get remove -y docker-ce docker-ce-cli containerd.io 
           sudo rm -rf /run/containerd 
      - run: sudo snap install --classic concierge
      - run: >
          sudo concierge prepare
          --juju-channel=3/stable
          --charmcraft-channel=3.x/stable
          -p "${{ matrix.preset }}"
      - run: >
          uvx tox -e integration
          --
          --log-cli-level=INFO -s
          --test-group-random-seed=0
          --test-group-count=4
          --test-group=${{ matrix.test-group }}
