name: Observability Charm Tests

on: [push, pull_request, workflow_call]

jobs:
  o11y-charm-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/alertmanager-k8s-operator
            commit: 90b85c79dfdeeeedcc538c92dcbc26fb2b931088  # rev114 2024-05-23T12:09:22Z
          - charm-repo: canonical/prometheus-k8s-operator
            commit: 41b10003b2e7aba34e26fa387af4297d97ecb535  # rev189 2024-05-21T21:25:20Z
          - charm-repo: canonical/grafana-k8s-operator
            commit: ec74910fc60848594ce44da3b549ad18aa6528aa  # rev113 2024-05-21T14:31:49Z
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.commit }}

      - name: Update 'ops' dependency in test charm to latest
        run: |
          sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
          echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        run: tox -vve unit

      - name: Run the charm's static analysis checks
        run: tox -vve static-charm
