name: Observability Charm Tests

on: [push, pull_request, workflow_call]

jobs:
  o11y-charm-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/alertmanager-k8s-operator
            tag: rev112
          - charm-repo: canonical/prometheus-k8s-operator
            tag: rev186
          - charm-repo: canonical/grafana-k8s-operator
            tag: rev112

    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.tag }}

      - name: Update 'ops' dependency in test charm to latest
        run: |
          sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
          echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        run: tox -vve unit

      - name: Run the charm's static analysis checks
        run: tox -vve static-charm
