---
on:
  pull_request:
    # for dev testing only
  push:
    # for dev testing only
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * SUN' # Sunday 6pm UTC, before international day starts

jobs:
  upgrade-pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install yaml

      - name: Show tags for commit
        uses: actions/github-script@v7
        with:
          script: |
            const {readFileSync, writeFileSync} = require('fs');
            const {parseDocument} = require('yaml');
            const space = ' ';

            const workflows = [
              '.github/workflows/db-charm-tests.yaml',
              '.github/workflows/hello-charm-tests.yaml',
            ];

            for (const workflow of workflows) {
              const doc = parseDocument(readFileSync(workflow, 'utf8'));

              // it's the first job that's parametrised with external repositories
              const job_name = doc.get('jobs').items[0].key.value;
              const include = doc.getIn(['jobs', job_name, 'strategy', 'matrix', 'include']);
              const repos = include.items
                .map(item => item.items.find(obj => obj.key.value === 'charm-repo').value.value)
                .map((item, idx) => [item, idx]);

              for (const [charm_repo, idx] of repos) {
                const node = doc.getIn(['jobs', job_name, 'strategy', 'matrix', 'include', idx, 'commit'], true);
                const {value: commit, comment} = node;
                const [owner, repo] = charm_repo.split('/');
                const details = await github.rest.repos.get({owner, repo });
                const branch = details.data.default_branch;

                const resp = await github.rest.repos.listCommits({owner, repo, per_page: 1});
                const new_commit = resp.data[0].sha;
                const timestamp = resp.data[0].commit.committer.date;
                
                const tags = await github.rest.repos.listTags({owner, repo});
                const matches = tags.data.filter(tag => tag.commit.sha === new_commit);
                const tag_line = matches.map(tag => tag.name).join(space);
                const new_comment = space + [tag_line, timestamp].filter(Boolean).join(space);

                node.value = new_commit;
                node.comment = new_comment;
              }
              writeFileSync(workflow, doc.toString(), 'utf8');
            }

      - run: git diff | cat  # debug only
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git switch -c auto-upgrade-external-charm-pins
          git commit -am "ci: upgrade external charm pins"
          git remote -v
      - run: |
          git push -uf origin auto-upgrade-external-charm-pins
