---
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * SUN' # Sunday 6pm UTC, before international day starts

jobs:
  upgrade-pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/update-charm-pins
        with:
          workflows: |-
            .github/workflows/db-charm-tests.yaml
            .github/workflows/hello-charm-tests.yaml
            .github/workflows/charmcraft-pack.yaml
            .github/workflows/observability-charm-tests.yaml
          gh-pat: ${{ secrets.UPDATE_CHARM_PINS_ACCESS_TOKEN }}

      - run: git diff | cat  # debug only
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git switch -c auto-upgrade-external-charm-pins
          git commit -am "ci: upgrade external charm pins"
          git remote -v
      - run: |  # debug
          curl -H "Authorization: token ${{ secrets.UPDATE_CHARM_PINS_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/ \
               -I | grep "x-oauth-scopes"
      - run: |
          # FIXME change personal fork to real upstream
          git remote add upstream "https://dimaqq:${{ secrets.UPDATE_CHARM_PINS_ACCESS_TOKEN }}@github.com/dimaqq/operator.git"
          git push -uf upstream auto-upgrade-external-charm-pins
      - run: |
          OPEN=$(gh pr list --state open --head auto-upgrade-external-charm-pins)
          test -n "$PR_URL" || gh pr create --base main --head auto-upgrade-external-charm-pins
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_CHARM_PINS_ACCESS_TOKEN }}
