---
name: Update Charm Pins

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * SUN' # Sunday 6pm UTC, before international day starts

jobs:
  upgrade-pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.UPDATE_CHARM_PINS_ACCESS_TOKEN }}

      - uses: ./.github/actions/update-charm-pins
        with:
          workflows: |-
            .github/workflows/db-charm-tests.yaml
            .github/workflows/hello-charm-tests.yaml
            .github/workflows/charmcraft-pack.yaml
            .github/workflows/observability-charm-tests.yaml
          gh-pat: ${{ secrets.UPDATE_CHARM_PINS_ACCESS_TOKEN }}

      - run: git diff | cat  # debug only
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          #git branch -d auto-upgrade-external-charm-pins || echo "no need for cleanup"
          git switch -C auto-upgrade-external-charm-pins
          git commit --allow-empty -am "ci: upgrade external charm pins"
          git push -f --set-upstream origin auto-upgrade-external-charm-pins
      - run: |
          OPEN=$(gh pr list --state open --head auto-upgrade-external-charm-pins)
          test -n "$PR_URL" || gh pr create --base main --head auto-upgrade-external-charm-pins --title "Update Charm Pins" --body "Update Charm Pins"
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_CHARM_PINS_ACCESS_TOKEN }}
