---
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * SUN' # Sunday 6pm UTC, before international day starts

jobs:
  upgrade-pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install yaml

      - uses: ./.github/actions/update-charm-pins
        with:
          workflow: .github/workflows/db-charm-tests.yaml

      - uses: ./.github/actions/update-charm-pins
        with:
          workflow: .github/workflows/hello-charm-tests.yaml

      - run: git diff | cat  # debug only
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git switch -c auto-upgrade-external-charm-pins
          git commit -am "ci: upgrade external charm pins"
          git remote -v
      - run: |
          git push -uf origin auto-upgrade-external-charm-pins
      - run: |
          echo "FIXME, to do"
          # if a PR doesn't exist, create it
          PR_URL=$(gh pr list --head auto-upgrade-external-charm-pins --json url --jq '.[0].url')
          if [ -z "$PR_URL" ]; then gh pr create --base main --head auto-upgrade-external-charm-pins
